### ISSUE TITLE
Error: No objects specified in config file

### ISSUE THREAD

**Issue by jkemp814** [CheariX/silverblue-akmods-keys#11]
Keep getting this error:

sudo kmodgenca

Error: No objects specified in config file
Error making certificate request
chmod: cannot access '/etc/pki/akmods/certs/HP-Z840-4080769880.*': No such file or directory
/usr/sbin/restorecon: lstat(/etc/pki/akmods/certs/HP-Z840-4080769880.der) failed: No such file or directory

It's like it is not creating the file `HP-Z840-4080769880.der` under certs, so the `public_key.der` is a broken link.

**Comment by CheariX** [comment]
Hm. Looks strange to me. Unfortunately, I have no idea what goes wrong there.
Since this issue is about `kmodgenca` and not about this project, I do not know how to help you.
For me, it worked.
Maybe you can have a look at RPM Fusions documentation: https://rpmfusion.org/Howto/Secure%20Boot

**Comment by jkemp814** [comment]
I used that link you posted in another response to make the .der .priv files and got it added to the secure boot database, I think. Everything went well with not errors.

I'm still getting that error where the system falls back to Nouveau. I removed and reinstalled the akmod-nvidia and xorg-x11-drv-nvidia-cuda packages. But it still falls back.

**Comment by jkemp814** [comment]
I check the signing. It returned a large block of hashes. Does that mean the driver is signed? That it maybe my graphics card need to be i9n legacy mode? Nvidia Titan X (Pascal)

**Comment by CheariX** [comment]
> I check the signing. It returned a large block of hashes. 

Yes, if you get a bunch of uppercase letters divided by colons, the module is signed.
Otherwise, the command will exit with an error (or an empty response?), if i remember correctly.

> That it maybe my graphics card need to be i9n legacy mode? Nvidia Titan X (Pascal)

Sorry, this is out of my expertise :(

**Comment by jkemp814** [comment]
Great little utility. Thank you for making it and sharing. It works great on my mobile workstation. I'll get a new graphics card for my main workstation. I appreciate all the responses.
