### ISSUE TITLE
Error while trying to use solution

### ISSUE THREAD

**Issue by OptimoSupreme** [CheariX/silverblue-akmods-keys#12]
On the last step `Build akmods-keys` while running `rpm-ostree install akmods-keys-0.0.2-8.fc$(rpm -E %fedora).noarch.rpm` I'm getting the following error:

```
justin@nazgul:~/git/silverblue-akmods-keys$ rpm-ostree install akmods-keys-0.0.2-8.fc$(rpm -E %fedora).noarch.rpm
Checking out tree 8ceba7f... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora copr:copr.fedorainfracloud.org:phracek:PyCharm google-chrome rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'updates' (cached); generated: 2024-01-10T01:04:09Z solvables: 18300
rpm-md repo 'fedora' (cached); generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'copr:copr.fedorainfracloud.org:phracek:PyCharm' (cached); generated: 2023-08-10T15:35:19Z solvables: 5
rpm-md repo 'google-chrome' (cached); generated: 2024-01-10T15:29:21Z solvables: 3
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2023-12-29T17:12:39Z solvables: 29
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2023-08-10T16:27:35Z solvables: 2
rpm-md repo 'updates-archive' (cached); generated: 2024-01-10T01:23:48Z solvables: 21716
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
error: Writing rpmdb: Error running transaction: file /usr/share/doc/perl-IO-Socket-SSL/README from install of perl-IO-Socket-SSL-2.083-3.fc39.noarch conflicts with file from package systemd-udev-254.7-1.fc39.x86_64
file /usr/share/doc/perl-podlators/README from install of perl-podlators-1:5.01-500.fc39.noarch conflicts with file from package systemd-udev-254.7-1.fc39.x86_64
file /usr/src/kernels/6.6.9-200.fc39.x86_64/arch/arm/mach-s5pv210/Makefile from install of kernel-devel-6.6.9-200.fc39.x86_64 conflicts with file from package python3-pycurl-7.45.2-5.fc39.x86_64
```

**Comment by CheariX** [comment]
AFAIK, this error message seem to be unrelated to this package.
It looks like any of your repositories is out of sync. You can try `rpm-ostree  refresh-md --force` and then reinstall `akmods-keys` again. Maybe, you also need to wait 1-2 days until upstream repositories are in sync again.

**Comment by OptimoSupreme** [comment]
Okay cool so refreshing my repos did fix that issue, and I was able to run `rpm-ostree install akmods-keys-0.0.2-8.fc$(rpm -E %fedora).noarch.rpm` and then after a reboot I installed `akmod-nvidia` and rebooted again. It's booting to a black screen now though. This attempt was made on a freshly installed and updated copy of Silverblue by the way so no holdovers from before.

**Comment by CheariX** [comment]
Did you apply kargs after installing `akmod-nvidia`?
```
  rpm-ostree kargs \
    --append-if-missing=rd.driver.blacklist=nouveau \
    --append-if-missing=modprobe.blacklist=nouveau \
    --append-if-missing=nvidia-drm.modeset=1 \
    --delete-if-present=nomodeset
```

**Comment by OptimoSupreme** [comment]
I had appended them all, but had not run `--delete-if-present=nomodeset` which seems like it did the trick! Thanks so much for helping me out with this.

I'm not sure if you consider these steps such as refreshing your repos and applying kargs outside the scope of this fix, but if not would you be open to a pr containing those two steps?

**Comment by CheariX** [comment]
Great to hear that it is now working. Thanks for your suggestion, but both issues you've experienced are clearly out of this projects scope (ostree, nvidia). These are things one get used to after some time of using Silverblue ^^
