### ISSUE TITLE
Support Fedora 37

### ISSUE THREAD

**Issue by arteeh** [CheariX/silverblue-akmods-keys#3]
I can confirm that this process works on the Fedora Silverblue 37 beta.

[This line](https://github.com/CheariX/silverblue-akmods-keys/blob/master/setup.sh#L10) could use some bash scripting to fetch the major Fedora version and insert it at the "fc36" part. Otherwise, just warn about the hardcoded number.

It would also be useful if [this part](https://github.com/CheariX/silverblue-akmods-keys/blob/master/README.md?plain=1#L36) of the readme had a note about the version number.

**Comment by CheariX** [comment]
Wow. I did not think about the hardcoded release number.
Fixed.
