### ISSUE TITLE
Provide a way to revert changes

### ISSUE THREAD

**Issue by CleoMenezesJr** [CheariX/silverblue-akmods-keys#8]
It would be nice to have a README section showing how to revert changes to the script and such.

**Comment by CheariX** [comment]
Sorry, I do not understand.
What exactly would you like to have?

- If you uninstall the package using `rpm-ostree uninstall`, there are, AFAIK, no "changes" left.
- `setup.sh` automatically cleans up `/root/rpmbuild`.
- The only thing left is the rpm file. The README advices to delete it after installation.

Feel free to provide more details, or even better, a PR.

**Comment by CheariX** [comment]
Closed due to missing information.
